languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Amazon RoboMaker Workshop"
theme = "learn"
uglyurls = false
googleAnalytics = "UA-44634850-4"
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
editURL = "https://github.com/jerwallace/aws-robomaker-workshops/edit/master/content/"
themeVariant = "mine"
showVisitedLinks = false
author = ""
description = "Amazon RoboMaker Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
ghrepo = "https://github.com/jerwallace/aws-robomaker-workshops/"
branch = "master"
template_bucket = "robomakerworkshop.com"

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
